name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Usar la última versión
      - name: Docker login
        uses: docker/login-action@v2  # Usando la acción oficial de login
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag camiloooo14/tutorial18:latest
      - name: Docker Push
        run: docker push camiloooo14/tutorial18:latest  # Corregido el comando
